name: Sync Santa Zuera Episodes

on:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  weekly-fetch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Fetch data from API
      run: |
        curl -sf "https://santa-zuera.vercel.app/api/sync"
